version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: tgru-raspap_server_1
      APP_PORT: 8081
    
  server:
    container_name: raspap
    image: ghcr.io/raspap/raspap-docker:latest
    #build: .
    ports:
      - "8081:8081"
    privileged: true
    network_mode: host
    cgroup: host # uncomment when using an ARM device
    environment:
      - RASPAP_SSID=raspap-webgui
      - RASPAP_SSID_PASS=ChangeMe
      - RASPAP_COUNTRY=GB
      - RASPAP_WEBGUI_USER=admin
      - RASPAP_WEBGUI_PASS=secret
      - RASPAP_WEBGUI_PORT=80
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    restart: unless-stopped
